### ISSUE TITLE
PreProcesamiento de los datos

### ISSUE THREAD

**Issue by rocio2403** [rocio2403/TPs-ALC-1C2024#22]

**Comment by rocio2403** [comment]
Consigna 1.- Leer los datos del archivo tabla nutricional.csv. Completar las
celdas faltantes con ceros. Poner todos los datos en la misma unidad.
Consigna 2.- Desarrollar una funci´on que reciba como par´ametro un DataFrame y que eval´ue si las cantidades de los principales elementos de la dieta, prote´ınas, carbohidratos, grasas, sodio, fibra, frutas y verduras, cumple los m´argenes
de ingesta de la OMS. Esta funci´on debe devolver VERDADERO si los cumple.
Verificar la Canasta B´asica con esta funci´on.

**Comment by rocio2403** [comment]
sobre consigna 2
pregunta en el foro : 
1-Cuando se refiere a grasas como elemento principal, se refiere a la fila Grasas Totales del cuadro 2 o también a los ácidos grasos?
 2- En el cuadro 2:
                             Asumimos que la suma de Cantidad de elementos en gramos equivale a 2700 kcal?
                              Para calcular "% de energía total" sumamos la cantidad de gramos de Prot/CH/Grasas y lo multiplicamos por su equivalencia en kcal(cada 1 gr de Prto/CH/grasas)?
3- Que quiere decir "%b"?
4- Para cada DataFrame que recibimos como sabemos la cantidad de kcal diarias?


Respuestas dadas:
1. Las grasas totales son la suma de los ácidos grasos, es decir, tu consumo de cada ácido graso en particular debe ser menor al porcentaje que te dan para cada uno pero además tu consumo total de grasas debe ubicarse entre 15 y 30%

2. Corrijanme si no entendí pero:  en el cuadro 2 está en porcentaje, como ustedes en la tabla 1 lo tienen en base a 2700 calorías, piensenlo como un porcentaje de estas 2700 calorias. Esto significa que sea un porcentaje de la energía total (Nuestra energía total en este caso son las 2700 calorias)

3. es un error de tipeo, iba %

4. Las 2700 calorías son de consumo diario. Si no me equivoco, todo el TP es en base al consumo diario.

**Comment by rocio2403** [comment]
si pongo todo en gramos, la suma da casi 2700 gr
investigar como se relacionan los gramos con las calorias

La relación entre gramos y calorías no es directa, ya que depende del tipo de macronutriente del que estemos hablando. Aquí te dejo una tabla para aclararlo:

Carbohidratos: 1 gramo = 4 calorías.
Proteínas: 1 gramo = 4 calorías.
Grasas: 1 gramo = 9 calorías.
Alcohol: 1 gramo = 7 calorías.
Ejemplo de Conversión:

**Comment by rocio2403** [comment]
respuestas del foro : AGNI no es un typo, y AGp son los poliinsaturados, en la tabla 1 figuran ambos por separado y tambien los acidos grasos saturados. En principio no están separados los agp 3 o 6 asumo que los juntan todos.

**Comment by rocio2403** [comment]
Las grasas totales incluyen las grasas saturadas, poliinsaturadas, monoinsaturadas y las grasas trans


fuente :https://www.fao.org/4/ac911s/ac911s00.pdf
![Image](https://github.com/rocio2403/TPs-ALC-1C2024/assets/132227093/df3833ce-beb8-4f1a-b0ab-0cf78fe42f81)

**Comment by IMAbril** [comment]
### Info sobre datos de índole nutricional en la tabla de Márgenes de la OMS

Entre los nutrientes que aportan calorías se encuentran los hidratos de carbono, proteínas y grasas. Por otro lado, no aportan calorías las vitaminas, minerales y el agua. (Página 18, Tésis)

Los nutrientes se pueden clasificar teniendo en cuenta las necesidades diarias en macronutrientes y micronutrientes. En los primeros se encuentran las proteínas, lípidos e hidratos de carbono. Los micronutrientes incluyen las
vitaminas y minerales.

 **Macronutrientes**

- Hidratos de carbono o carbohidratos: **Los carbohidratos aportan 4 Kcal/g** y el Comité FAO/OMS (2003) recomienda
una ingesta de 55% a 75% del total de la energía consumida, mientras que del total
de hidratos de carbono, sólo un 10% deben ser simples. Con respecto a las recomendaciones del consumo de **fibra**, se estima que el aporte de la misma debe ser de **25 a 35 gr diarios o 10 a 13 g/1000 Kcal** 

> Se pueden clasificar según el número de moléculas o dependiendo si son
> simples o complejos.
>
> Según número de moléculas:
> • Monosacáridos: glucosa, fructosa, galactosa;
> • Disacáridos: sacarosa (azúcar de mesa), lactosa, maltosa;
> • Oligosacáridos: estaquiosa, verbascosa, rafinosa
> • Polisacáridos: amiláceos o almidón, polisacáridos no amiláceos (PNA),
> Solubles (pectinas, los beta glucanos y gomas). Insolubles (celulosa y
> la hemicelulosa)
> 
> Según simples o complejos: los hidratos de carbono simples son los monosacáridos y disacáridos, que los encontramos en los dulces compactos, mermeladas, jaleas, azúcar y miel. Los hidratos de carbono complejos se encuentran en alimentos como los cereales y sus derivados, legumbres y hortalizas.


- Proteinas: produce alrededor de 4 kcal/g.

> En los adultos, el Informe de la Reunión de Expertos FAO/OMS/UNO 2001sobre Necesidades de Energía y Proteínas considera que el consumo adecuado de proteína es de 0,8 g/k para mujeres y de 0,85 g/k para varones. Asimismo, la FAO/OMS (2003) establece que el aporte diario máximo de proteínas puede estar representado por un **15% del total de calorías**.


- Grasas: produce alrededor de 9 kcal/g. La OMS/FAO en el informe sobre Dieta, Nutrición y Prevención de
enfermedades crónicas (3) recomienda limitar el consumo diario de grasas a un segmento entre 15 y 30% de la ingesta diaria de energía, y a menos del 10%, el consumo de grasas saturadas. Con respecto al colesterol se recomienda un
consumo menor a 300 mg/día
> NOTA (ChatGPT): Colesterol: Aunque es químicamente una grasa, no se descompone ni se oxida para liberar energía. Se transporta en el cuerpo a través de las lipoproteínas (como LDL y HDL) y se utiliza en procesos biológicos que no involucran la producción de energía calórica.

**Comment by rocio2403** [comment]
Estimadas y estimados,

En el labo de ayer estuvimos viendo con varios grupos sobre como validar los objetivos de la OMS.

El asunto es que, si tomamos como el total de lo consumido en un día sumando la columna 'Cantidades' en gramos, no vamos a entrar nunca en los objetivos.

Estuve mirando bien los datos y me dí cuenta que al usar este total para el cálculo de los porcentajes estamos incorporando el peso en líquido de muchos alimentos que no tiene relación con calorías (el agua no tiene calorías ni nutrientes).

Dicho esto, el total para calcular los porcentajes tiene que ser tomado del TOTAL en gramos de los nutrientes de cada alimento.

O sea, sumando las otras columnas, no la primera (ojo con las grasas, solo se suma la grasa total, no las otras).

Ahí debería dar la cuenta de los objetivos OMS. Disculpen a los que ayer les dije otra cosa

Saludos y buen finde.
